---
title: "hw-5"
author: "Hector He"
date: "5/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pokemon <- read.csv('~/Desktop/Spring 2022/PSTAT 131/homework/homework-5/data/Pokemon.csv')
library(tidymodels)
library(tidyverse)
library(readr)
library(dplyr)
head(pokemon, n = 8)
```

```{r}
library(janitor)
pokemon <- clean_names(pokemon)
head(pokemon)
```

```{r}
#ggplot(data = pokemon, aes(x = type_1)) + geom_bar()
ggplot(data = pokemon, aes(x = reorder(factor(type_1), type_1, function(x)-length(x)))) + geom_bar() + labs(x = 'type_1')
```
Type 1 Poison, Fighting, Steel, Ice, Fairy, Flying have less than 30 counts, especially Type 1 Flying has less than 10 counts

```{r}
pokemon <- filter(pokemon, type_1=='Bug'|type_1=='Fire'|type_1=='Grass'|type_1=='Normal'|type_1=='Water'|type_1=='Psychic')
pokemon
```

```{r}
pokemon <- pokemon %>%
  mutate(type_1 = factor(type_1)) %>%
  mutate(legendary = factor(legendary))
pokemon
```
```{r}
set.seed(2000)
pokemon_split <- initial_split(pokemon, prop = 0.75, strata = type_1)
pokemon_test <- testing(pokemon_split)
pokemon_train <- training(pokemon_split)
```

```{r}
dim(pokemon_train)
dim(pokemon_test)
```
```{r}
pokemon_folds <- vfold_cv(pokemon_train, v = 5, strata = type_1)
pokemon_folds
```
```{r}
pokemon_recipe <- recipe(type_1 ~ legendary+generation+sp_atk+attack+speed+defense+hp+sp_def, data = pokemon_train) %>% 
  step_dummy(c(legendary, generation)) %>%
  step_center(all_predictors()) %>% 
  step_scale(all_predictors()) 
```






